---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install OpenJDK 11
  apt:
    name: openjdk-11-jdk
    state: present

- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present

- name: Set Java 17 as the default
  alternatives:
    name: java
    path: /usr/lib/jvm/java-17-openjdk-amd64/bin/java
    priority: 1711
  when: ansible_facts.os_family == "Debian"

- name: Set javac 17 as the default
  alternatives:
    name: javac
    path: /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
    priority: 1711
  when: ansible_facts.os_family == "Debian"

