---
- name: Reboot control plane and worker nodes
  hosts: control_plane:worker_nodes
  become: yes
  tasks:
    - name: Reboot the system
      command: sudo reboot now
      async: 1
      poll: 0
      ignore_errors: true

