---
- name: Setup kubeconfig for jenkins on worker nodes
  hosts: worker_nodes
  become: yes
  tasks:
    - name: Create .kube directory in jenkins home
      file:
        path: /home/jenkins/.kube
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'

    - name: Move kube config to .kube directory
      command: mv /home/jenkins/config /home/jenkins/.kube/config
      become_user: jenkins

    - name: Set ownership of .kube directory
      file:
        path: /home/jenkins/.kube
        state: directory
        owner: jenkins
        group: jenkins
        recurse: yes

    - name: Ensure .bashrc contains KUBECONFIG export
      lineinfile:
        path: /home/jenkins/.bashrc
        line: 'export KUBECONFIG=~/.kube/config'
        create: yes
        owner: jenkins
        group: jenkins
        mode: '0644'

